### ISSUE TITLE
'QRCode' was not declared in this scope?

### ISSUE THREAD

**Issue by HamishMacEwan** [arcbtc/LNURLPoS#1]
Hi,

I've checked that I followed the instructions and I have Googled for this error, but none of the results seem conclusive or apply. 

It's my first time with the Arduino IDE, but it seems to have found and I've installed the libraries required, and though I'm still waiting for the hardware, thought I'd get about preparing for its arrival by verifying, by compilation, the set up.

![javaw_APOakbDu48](https://user-images.githubusercontent.com/388061/135222574-dbc5dcba-f2af-4307-af4f-105aa0103ca4.png)

If there's any additional information required, please advise.

**Comment by arcbtc** [comment]
Thanks Hamish!
You need to copy the libraries into you arduino core libraries folder.
Open File>Examples>Basic>Blink
Go to Sketch>Show sketch foler
Now you have your Arduino install folder, go down a few levels
![image](https://user-images.githubusercontent.com/33088785/135330838-d34ea531-81d7-48c1-9b67-72c1fab72ecd.png)
Then place the projects libraries in the core libraries folder:
![image](https://user-images.githubusercontent.com/33088785/135330963-2b39124c-14a5-468f-85ae-6a3805279a8d.png)
Should be gravy now!

**Comment by HamishMacEwan** [comment]
Thanks very much for the instructions.  It has led to a long and frustrating encounter with Windows 10 permissions.

The directory for the installation as derived from your guidance above is:

`C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.51.0_x86__mdqgnx93n4wtt\libraries`

All attempts to copy the files there have been met with refusal and my permissions foo has not been very successful, though I do now "own" the WindowsApps folder, to no useful effect.

Currently I have the additional libraries in a more accessible folder and for all but the QRCode library that appears to be working:

```
Using library SPI at version 2.0.0 in folder: C:\Users\User\OneDrive\Documents - Old\ArduinoData\packages\esp32\hardware\esp32\2.0.0\libraries\SPI 

Using library TFT_eSPI at version 2.2.20 in folder: C:\Users\User\OneDrive\Documents - Old\Arduino\libraries\TFT_eSPI 

Using library FS at version 2.0.0 in folder: C:\Users\User\OneDrive\Documents - Old\ArduinoData\packages\esp32\hardware\esp32\2.0.0\libraries\FS 

Using library SPIFFS at version 2.0.0 in folder: C:\Users\User\OneDrive\Documents - Old\ArduinoData\packages\esp32\hardware\esp32\2.0.0\libraries\SPIFFS 

Using library Keypad at version 3.1.1 in folder: C:\Users\User\OneDrive\Documents - Old\Arduino\libraries\Keypad 

Using library uBitcoin at version 0.1.2 in folder: C:\Users\User\OneDrive\Documents - Old\Arduino\libraries\uBitcoin 
```

There is a collision at:
![explorer_2ZRcJtRtTK](https://user-images.githubusercontent.com/388061/135356999-fa1aeda2-c980-4d8f-8189-0515d18f0482.png)

That is another `qrcode.h` at `C:\Users\User\OneDrive\Documents - Old\ArduinoData\packages\esp32\hardware\esp32\2.0.0\tools\sdk\esp32\include\qrcode\include` which is fulfilling the `#include` though not usefully.

Is there are way to specify exactly the order of paths to search or include a path in the `#include` syntax?

**Comment by babysnakeum** [comment]
FYI I'm observing the same issue on mac, even after copying the libraries into arduinos core libraries folder

**Comment by HamishMacEwan** [comment]
```
Arduino: 1.8.16 (Windows 10), Board: "TTGO LoRa32-OLED V1, 80MHz, 921600, None"

c:/users/user/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/gcc8_4_0-esp-2021r1/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\User\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.0/tools/sdk/esp32/lib\libwpa_supplicant.a(crypto_mbedtls.c.obj): in function `hmac_sha256':

/home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/wpa_supplicant/src/crypto/crypto_mbedtls.c:254: multiple definition of `hmac_sha256'; libraries\uBitcoin\utility\trezor\hmac.c.o:C:\Program Files (x86)\arduino-1.8.16\libraries\uBitcoin\src\utility\trezor/hmac.c:67: first defined here

collect2.exe: error: ld returned 1 exit status

exit status 1

Error compiling for board TTGO LoRa32-OLED V1.
```

Different error, so one thing is solved.

**Comment by ShelbyApp** [comment]
I've put the QRCode library in every libraries folder that exists and still have this problem.

I can even click Sketch->Include Library->QRCode which includes <qrcode.h> and still get the problem

I can access the QRCode example through the Arduino software and that won't compile either (Same error)

Seems like there is a bigger problem going on?

**Comment by citizenanalog** [comment]
> I've put the QRCode library in every libraries folder that exists and still have this problem.
> 
> I can even click Sketch->Include Library->QRCode which includes <qrcode.h> and still get the problem
> 
> I can access the QRCode example through the Arduino software and that won't compile either (Same error)
> 
> Seems like there is a bigger problem going on?

I had to switch to MacOS and had to add the libraries manually but eventually got it to work. Still no luck on Ubuntu.

**Comment by ShelbyApp** [comment]
I moved the QRCode to the local folder with "qrcode.h" and got it to work

but now I am getting the redundant sha256 error now  :(  Did you have that one?

c:/users/jason/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/gcc8_4_0-esp-2021r1/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\Jason\Documents\Arduino\hardware\espressif\esp32/tools/sdk/esp32/lib\libwpa_supplicant.a(crypto_mbedtls.c.obj): in function `hmac_sha256':

/Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/wpa_supplicant/src/crypto/crypto_mbedtls.c:254: multiple definition of `hmac_sha256'; libraries\uBitcoin\utility\trezor\hmac.c.o:C:\Program Files (x86)\Arduino\libraries\uBitcoin\src\utility\trezor/hmac.c:67: first defined here
collect2.exe: error: ld returned 1 exit status

**Comment by ShelbyApp** [comment]
DING DING DING

If you go to utilities/trezor/hmac.c

There are 2 definitions of the following, just delete 1 and should be good to go 


void hmac_sha256(const uint8_t *key, const uint32_t keylen, const uint8_t *msg, const uint32_t msglen, uint8_t *hmac)
{
	static CONFIDENTIAL HMAC_SHA256_CTX hctx;
	hmac_sha256_Init(&hctx, key, keylen);
	hmac_sha256_Update(&hctx, msg, msglen);
	hmac_sha256_Final(&hctx, hmac);
}

**Comment by claytantor** [comment]
so I think I _may_ know what the problem is, `QRCode` as a directory name instead of all lower case `qrcode` to match the import may be an issue with my version of the compiler finding the import of `qrcode.h`. I made my library name all lower case and it seems to be properly importing now.

**Comment by trbouma** [comment]
> DING DING DING
> 
> If you go to utilities/trezor/hmac.c
> 
> There are 2 definitions of the following, if you delete 1 then it should work.
> 
> ** It looks like one is for confidential addresses and the other for basic
> 
> void hmac_sha256(const uint8_t *key, const uint32_t keylen, const uint8_t *msg, const uint32_t msglen, uint8_t *hmac) { **static CONFIDENTIAL HMAC_SHA256_CTX hctx;** hmac_sha256_Init(&hctx, key, keylen); hmac_sha256_Update(&hctx, msg, msglen); hmac_sha256_Final(&hctx, hmac); }
> 
> void hmac_sha512(const uint8_t *key, const uint32_t keylen, const uint8_t *msg, const uint32_t msglen, uint8_t *hmac) { **HMAC_SHA512_CTX hctx;** hmac_sha512_Init(&hctx, key, keylen); hmac_sha512_Update(&hctx, msg, msglen); hmac_sha512_Final(&hctx, hmac); }
> 
> ![IMG_0467](https://user-images.githubusercontent.com/89351907/140822052-0d44ee19-7faa-40d3-b871-4789fa3009f5.jpg)

Hi I successfully got to this point then encountered this error below. I am running Ubuntu 20

Arduino: 1.8.18 (Linux), Board: "TTGO LoRa32-OLED V1, 80MHz, 921600, None"

Traceback (most recent call last):
  File "/home/trbouma/.arduino15/packages/esp32/tools/esptool_py/3.1.0/esptool.py", line 38, in <module>
    import serial
ImportError: No module named serial
exit status 1
Error compiling for board TTGO LoRa32-OLED V1.


This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
